import type { Metadata } from "next";
// import localFont from "next/font/local";
import "@/app/global.css";
import { Abril_Fatface, Open_Sans } from "next/font/google";

import ClientProviders from "@/contexts/ClientProviders";
import Header from "@/components/Header";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const abrilFatface = Abril_Fatface({
  weight: "400",
  subsets: ["latin"],
});

const OpenSans = Open_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={OpenSans.className}>
        <Header />
        <ClientProviders>{children}</ClientProviders>
        {/* {children} */}
      </body>
    </html>
  );
}
